pipeline {
    agent any
    tools {
        maven 'Maven_3.9.4'
        jdk 'JDK11'
    }
    triggers {
        githubPush()   // listens for GitHub push events
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'test/e2e_UI', url: 'https://github.com/ankititmuniversity/eCommerce_Selenium_TestNG.git'
            }
        }
        stage('Build & Test') {
            steps {
                sh 'mvn clean test -f e-commerce/pom.xml' 
            }
        }
    }
}